---
- name: check if operating system is supported
  assert: that="ansible_os_family == 'RedHat'" 

- name: install dependencies
  yum: name={{ item }}
  with_items:
    - openssh-server
    - postfix
  become: yes

- name: enable dependencies
  service: name={{ item }} state=running enabled=yes
  with_items:
    - sshd
    - postfix
  become: yes

- name: install gitlab
  yum: name={{ gitlab_omnibus_package_url }}
  become: yes
  register: gitlab
  notify: restart gitlab

- name: template gitlab.rb
  template: src=gitlab.rb dest=/etc/gitlab/gitlab.rb
  become: yes
  register: gitlab_rb
  notify: restart gitlab

- name: configure gitlab
  command: gitlab-ctl reconfigure
  become: yes
  when: gitlab|changed or gitlab_rb|changed
  notify: restart gitlab

- name: open firewall ports
  firewalld: port={{ item }} permanent=true state=enabled
  with_items:
    - 22/tcp
    - 80/tcp
    - 443/tcp
  become: yes
  notify: reload firewall

- name: start gitlab
  command: gitlab-ctl start
  become: yes
