---
- include: csgoserver.yml
- include: tf2server.yml
- include: arma3server.yml
- include: archlinux.yml
- include: murmur.yml
- include: teamspeak.yml
- include: gitlab.yml
- include: git-annex.yml
