---
- name: ensure operating system is supported
  assert: that="ansible_os_family == 'RedHat'"

- name: install git-annex
  yum: name=git-annex
  sudo: yes

- name: create user
  user: name=git createhome=yes
  sudo: yes

- name: display further instructions
  debug: msg="Copy SSH keys to server to continue"
