---
- name: check if operating system is supported 
  assert: that="ansible_os_family == 'Debian'

- name: perform safe upgrade of all packages
  apt: update_cache=yes upgrade=safe
  become: yes

- name: install ntp
  apt: name=ntp
  become: yes

- name: enable network time
  service: name=ntp state=started enabled=yes
  become: yes

- name: install fail2ban
  apt: name=fail2ban
  become: yes

- name: enable fail2ban
  service: name=fail2ban state=started enabled=yes
  become: yes

- name: enable SSH
  service: name=ssh state=started enabled=yes
  become: yes