---
- name: open firewall ports for Source Dedicated Server
  firewalld: port={{ item }} permanent=true state=enabled
  with_items:
    - 27015/tcp # Game
    - 27015/udp # Game
    - 27020/udp # SourceTV
