---
- name: install mumble server
  apt: name=mumble-server
  become: yes

- name: template murmur.ini
  template: src=murmur.ini dest=/etc/murmur.ini
  become: yes

- name: set mumble superuser password
  command: murmurd -supw {{ murmur_superuser_password }}
  become: yes

- name: enable mumble server
  service: name=mumble-server state=started enabled=true
  become: yes
  notify:
    - restart murmur
